### ISSUE TITLE
Error when trying to rerun the DDI-CYP3A4 qualification workflow

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#1262]
Workflow input is [here](https://github.com/Yuri05/TestReport/releases/download/vTralala/07_4mail.7z)
```
i Info	Starting run of Calculate PK Parameters task for Cimetidine-Alprazolam-DDI-Pourbaix 1985 - Alprazolam 0.5 mg TID control
29/07/2024 - 20:08:16
! Warning	Type:    System.ArgumentOutOfRangeException
Message: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Method:  Void ThrowArgumentOutOfRange_IndexMustBeLessException()
Stack trace:
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at OSPSuite.Core.Domain.Services.PKValuesCalculator.setMultipleDosingPKValues(ICache`2 pk, IReadOnlyList`1 allIntervals, PKCalculationOptions options)
   at OSPSuite.Core.Domain.Services.PKValuesCalculator.CalculatePK(IReadOnlyList`1 time, IReadOnlyList`1 concentration, PKCalculationOptions options, IReadOnlyList`1 userDefinedPKParameters)
   at OSPSuite.Core.Domain.Services.PKAnalysesTask.<>c__DisplayClass8_0.<addPKParametersForOutput>b__1(IndividualResults individualResult)
   at OSPSuite.Core.Domain.Services.PKAnalysesTask.scaledIndividualIteration(IModelCoreSimulation simulation, SimulationResults simulationResults, Action`1 performIndividualScalingAction, String moleculeName, PKCalc
	
> Error Trace
	 ↪ createQualificationReport(qualificationRunnerFolder = "C:/CompletSetup_SBSuite/QualificationFramework/Version_3.1/QualificationRunner_11.1.130/", 
	  ↪ workflow$runWorkflow()
	   ↪ self$calculatePKParameters$runTask(self$simulationStructures)
	    ↪ self$getTaskResults(structureSet = set, settings = self$settings)
	     ↪ calculatePKAnalyses(results = simulationResults)
	      ↪ pkAnalysisTask$call("CalculateFor", calculatePKAnalysisArgs)
	       ↪ do.call(".External", c(list("r_call_method", self$pointer, methodName), 
Error: Type:    System.ArgumentOutOfRangeException
Message: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Method:  Void ThrowArgumentOutOfRange_IndexMustBeLessException()
Stack trace:
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at OSPSuite.Core.Domain.Services.PKValuesCalculator.setMultipleDosingPKValues(ICache`2 pk, IReadOnlyList`1 allIntervals, PKCalculationOptions options)
   at OSPSuite.Core.Domain.Services.PKValuesCalculator.CalculatePK(IReadOnlyList`1 time, IReadOnlyList`1 concentration, PKCalculationOptions options, IReadOnlyList`1 userDefinedPKParameters)
   at OSPSuite.Core.Domain.Services.PKAnalysesTask.<>c__DisplayClass8_0.<addPKParametersForOutput>b__1(IndividualResults individualResult)
   at OSPSuite.Core.Domain.Services.PKAnalysesTask.scaledIndividualIteration(IModelCoreSimulation simulation, SimulationResults simulationResults, Action`1 performIndividualScalingAction, String moleculeName, 
In addition: Warning messages:
1: package ‘ospsuite’ was built under R version 4.4.1 
2: package ‘rSharp’ was built under R version 4.4.0 
3: In toUnit(quantityOrDimension = quantityOrDimension, values = values,  :
  strings not representable in native encoding will be translated to UTF-8
4: In toUnit(quantityOrDimension = quantityOrDimension, values = values,  :
  input string 'Âµ|Î¼|µ' cannot be translated to UTF-8, is it valid in 'UTF-8' ?
5: In toUnit(quantityOrDimension = quantityOrDimension, values = values,  :
```

**Comment by Yuri05** [comment]
@pchelle Is this fixed now?

**Comment by pchelle** [comment]
> @pchelle Is this fixed now?

Not yet. But I think I have found the issue: In PR #1240, we fixed the conversion bug of simulation set `endTime`.
However, the qualification workflow creates simulation sets for DDI that use `endTime` in base unit (in `min`) while the simulation set default time unit is actually `h`.

In the current issue, the simulation initially had `endTime=14400 min` which is now `endTime=14400 h`.
But, the simulation results that were not re-run in this workflow still has `endTime=14400 min`.

> [!CAUTION]
> There is currently no warning when importing the simulation results when there is such a mismatch, but it crashed the calculation of the PK parameters.

**Comment by Yuri05** [comment]
> In the current issue, the simulation initially had `endTime=14400 min` which is now `endTime=14400 h`.
> But, the simulation results that were not re-run in this workflow still has `endTime=14400 min`.

??
In the qualification workflow, end times are defined with units, e.g.:
```
                "Output": "Organism|PeripheralVenousBlood|Alprazolam|Plasma (Peripheral Venous Blood)",
                "ObservedData": "DDI Ratios",
                "ObservedDataRecordId": 1340,
                "SimulationControl": {
                  "Project": "Cimetidine-Alprazolam-DDI",
                  "Simulation": "Pourbaix 1985 - Alprazolam 0.5 mg TID control",
                  "StartTime": 168,
                  "EndTime": 240,
                  "TimeUnit": "h"
                },
                "SimulationDDI": {
                  "Project": "Cimetidine-Alprazolam-DDI",
                  "Simulation": "Pourbaix 1985 - alprazolam 0.5 mg TID + cimetidine 200/400 mg QID",
                  "StartTime": 336,
                  "EndTime": 408,
                  "TimeUnit": "h"
                }
```

**Comment by pchelle** [comment]
Indeed, but the issue happens after (see code below):
- 1.  `minimumSimulationEndTime` is in base unit and converted appropriately from the configuration plan
- 2. PopulationSimulationSet assumes that time is in hour by default.

https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/blob/8f16b740fb77b08ea53ea02d71aa74d0c9ef112b/R/utilities-qualification.R#L59-L65
